name: CmdUI
version: 1.0.0
main: com.putopug.cmdui.CmdUI
api-version: 1.16
authors: [ PugzAreCute ]
description: A simple plugin to
commands:
  cmdui:
    description: Open the CMD UI
    usage: /<Command>
    permission: cmdui.opencmdui
    permission-message: §cSorry! You don't have permissions to use this command, if you think this is a mistake please contact the admins of this server!
  cmdreload:
    usage: /cmdreload
    description: Reload CmdUI from ìts configs!
    permission: cmdui.reload